version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

aliases:
  - &checkout
    checkout

run_yarn: &run_yarn
  name: Install yarn packages
  command: yarn install --frozen-lockfile

save_git: &save_git
  save_cache:
    name: Save Git Cache
    key: git-code-{{ .Revision }}
    paths:
      - .git
      - ~/.ssh

save_yarn: &save_yarn
  save_cache:
    name: Save Yarn Package Cache
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - node_modules

restore_git: &restore_git
  restore_cache:
    name: Restore Git Cache
    key: git-code-{{ .Revision }}

restore_yarn: &restore_yarn
  restore_cache:
    name: Restore Yarn Package Cache
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

commands:
  greenkeeper_update:
    steps:
    - *checkout
    - <<: [*restore_git, *restore_yarn]
    - run:
        name: update lockfile
        command:
          export PATH=$PATH:$(yarn global bin) &&
          yarn global add greenkeeper-lockfile@2 &&
          greenkeeper-lockfile-update
    - run:
        name: Install dependencies
        command: yarn install --frozen-lockfile
    - <<: [*save_yarn, *save_git]
  nodejs:
    steps:
    - *checkout
    - <<: [*restore_git, *restore_yarn]
    - run:
        <<: *run_yarn
    - run:
        name: Linting
        command: yarn lint
    - run:
        name: Testing
        command: yarn test --collectCoverage
    - store_artifacts:
        path: coverage
    - codecov/upload:
        file: coverage/*.json
  greenkeeper_upload:
    steps:
    - *checkout
    - <<: [*restore_git, *restore_yarn]
    - run:
        name: Upload lockfile
        command:
          export PATH=$PATH:$(yarn global bin) &&
          yarn global add greenkeeper-lockfile@2 &&
          greenkeeper-lockfile-update

# List of jobs
jobs:
  lockfile_update:
    docker:
      - image: circleci/node:10
    steps:
      - greenkeeper_update
  node-v10:
    docker:
      - image: circleci/node:10
    steps:
      - nodejs
  node-v11:
    docker:
      - image: circleci/node:11
    steps:
      - nodejs
  node-v12:
    docker:
      - image: circleci/node:12
    steps:
      - nodejs
  lockfile_upload:
    docker:
      - image: circleci/node:10
    steps:
      - greenkeeper_upload

workflows:
  version: 2
  node-multi-build:
    jobs:
      - lockfile_update
      - node-v10:
          requires:
            - lockfile_update
      - node-v11:
          requires:
            - lockfile_update
      - node-v12:
          requires:
            - lockfile_update
      - lockfile_upload:
          requires:
            - lockfile_update
            - node-v10
            - node-v11
            - node-v12